# Generated by Django 3.0.3 on 2020-03-27 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Music Genre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(help_text='Stage Name', max_length=20)),
                ('first_name', models.CharField(help_text='First Name', max_length=20)),
                ('last_name', models.CharField(help_text='Last Name', max_length=20)),
                ('career_start', models.DateField(blank=True, null=True)),
                ('career_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['stage_name', 'career_start'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Track Name', max_length=50)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Say something about this track', max_length=1000)),
                ('number_of_listener', models.IntegerField(default=0, editable=False)),
                ('genre', models.ManyToManyField(help_text='Select a genre of music', to='music_center.Genre')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_center.Producer')),
            ],
            options={
                'ordering': ['name', 'number_of_listener', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_center.Track')),
            ],
            options={
                'ordering': ['track'],
            },
        ),
    ]
